import { Box, Container } from "@mui/material";
import { Inter } from "next/font/google";
import Banner from "../../components/Banner";
import Footer from "../../components/Footer";
import Offers from "../../components/Offers";
import Smallcard from "../../components/Smallcard";
import SmallCards from "../../components/Smallcards";
import Topnav from "../../components/Topnav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Topnav></Topnav>
        <Container>It all starts here!</Container>
      </body> */}
      <Topnav></Topnav>
      <Banner></Banner>
      <Box mt={2}></Box>
      <Container>
        <SmallCards></SmallCards>
        {/* <Box display={"flex"} flexDirection={"row"}>
          <Smallcard></Smallcard>
          <Box mx={2}></Box>
          <Smallcard></Smallcard>
        </Box> */}
        {/* <Carousel>
          <Smallcard />
          <Smallcard />
          <Smallcard />
        </Carousel> */}
        <Box mt={2}></Box>
        <Offers></Offers>
        <Box mt={2}></Box>
        <Footer></Footer>
      </Container>
    </>
  );
}
